version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python && /home/circleci/.poetry/bin/poetry config virtualenvs.create true && /home/circleci/.poetry/bin/poetry config virtualenvs.in-project true
            /home/circleci/.poetry/bin/poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
      - run:
          command: |
            /home/circleci/.poetry/bin/poetry run flake8
          command: |
            cp website/settings.py.sample website/settings.py
            cat >>website/settings.py <<END
            TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
            TEST_OUTPUT_VERBOSE = 2
            TEST_OUTPUT_DIR = 'test-results'
            END
            /home/circleci/.poetry/bin/poetry run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
destination: tr1
